### ISSUE TITLE
Using multiple URLs with individual includes does not work

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-stack-hub#19]
When a config file is created that uses multiple URLs to build the consolidated index and the URLS specify to include a specific stack, this does not work correctly.  For example this config:
```
# Configuration for the default Kabanero stack hub
name: Kabanero Stack Hub
description: This is the default stack hub for Kabanero
version: 0.9.0-rc.1
stacks:
  - name: kabanero-stack-hub
    repos:
      - url: https://github.com/kabanero-io/collections/releases/download/0.9.0-rc.1/java-spring-boot2-0.3.29-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.9.0-rc.1/nodejs-0.3.6-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.9.0-rc.1/nodejs-express-0.4.8-index.yaml
      - url: https://github.com/appsody/stacks/releases/download/quarkus-v0.3.3/incubator-index.yaml
        include:
          - quarkus
      - url: https://github.com/appsody/stacks/releases/download/java-openliberty-v0.2.11/incubator-index.yaml
        include:
          - java-openliberty
image-org:
image-registry:
nginx-image-name:
``` 
adds both the quarkus and java-openliberty stacks from the last URL specified rather than just including the java-openliberty stack.
